version: '3'
services:
  web:
    # requires to git clone https://github.com/jrsalgado/web-app-demo.git
    build:
      context: ./app/web-app-demo/
      # by default build search for Dockerfile in your context
      dockerfile: Dockerfile
    image: jsalgado/appdemoinfra_web_dev:latest
    environment:
       REACT_APP_API_URL: http://localhost:3101
       REACT_APP_ADMIN_URL: http://localhost:82
    volumes:
      - ./app/web-app-demo:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - "81:3000"
    command: [npm, start]
  admin:
    # requires to git clone https://github.com/jrsalgado/admin-demo.git
    build:
      context: ./app/admin-demo/
      # by default build search for Dockerfile in your context
      dockerfile: Dockerfile
    image: jsalgado/appdemoinfra_admin_dev:latest
    environment:
       REACT_APP_API_URL: http://localhost:3101
    volumes:
      - ./app/admin-demo:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - "83:3000"
    command: [npm, start]
  api:
    # requires to git clone https://github.com/jrsalgado/api-demo.git
    build: ./app/api-demo/
    image: jsalgado/appdemoinfra_api_dev:latest
    volumes:
      - ./app/api-demo:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - "3101:3100"
    depends_on:
      - db
    networks:
      - backend
    command: [npm, run, develop]
  db:
    image: mongo
    ports:
      - "27117:27017"
    networks:
      - backend

networks:
  backend:


# build service images
# $ docker-compose -f docker-compose.yml -f develop.yml build

# build individual service images
# $ docker-compose -f docker-compose.yml -f develop.yml build [service name]

# run services
# $ docker-compose -f docker-compose.yml -f develop.yml up

# remove services
# $ docker-compose -f docker-compose.yml -f develop.yml down